### ISSUE TITLE
1431. Kids With the Greatest Number of Candies

### ISSUE THREAD

**Issue by DonXavierdev** [DonXavierdev/Leetcode-Solutions#3]

**Comment by DonXavierdev** [comment]
'''result=[]
candies = [2,3,5,1,3]
extraCandies = 3
for i in candies:
    if i+extraCandies>=max(candies):
        result.append('true')
    else:
        result.append('false')
print(result)'''
 
i have solved the problem but confused about the fact that while i return the list named 'result' , it doesnt append 'false' into the list and automatically appends all the values as 'true', but when i used print() it was correct, the solution was that i append the keywords TRUE and False, not use 'true' and 'false', why is it like that

**Comment by mathew-alex** [comment]
In python, boolean values are `True` and `False`. 
The keywords are case-sensitive.

`result.append('true')`
Here you are not appending a boolean value but a string value, "true". Even if you type `result.append("True")` with the correct case , since the token (in this case, "True") is within quotation, it will be considered as a string.

correct usage is `result.append(True)`
